# Generated by Django 4.0.4 on 2022-12-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0002_entry_city_entry_country_entry_day_entry_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='password',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
