# Generated by Django 4.0.4 on 2022-12-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0003_entry_password_alter_entry_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='password',
            new_name='passwords',
        ),
    ]
