# Generated by Django 4.0.4 on 2022-12-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0004_rename_password_entry_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='passwords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
