# Generated by Django 4.0.4 on 2022-12-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0005_alter_entry_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='passwords',
        ),
    ]
