# Generated by Django 4.0.4 on 2022-12-26 09:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0006_remove_entry_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
