# Generated by Django 4.0.4 on 2022-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0008_alter_entry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=20),
        ),
    ]
