# Generated by Django 4.0.4 on 2022-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0009_alter_entry_contact_alter_entry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
