# Generated by Django 4.0.4 on 2022-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0010_alter_entry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
