# Generated by Django 4.0.4 on 2022-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0014_alter_entry_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='document',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
