# Generated by Django 4.0.4 on 2022-12-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0015_alter_entry_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='document',
            new_name='documents',
        ),
    ]
