# Generated by Django 4.0.4 on 2022-12-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0016_rename_document_entry_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='passwords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
