# Generated by Django 4.0.4 on 2022-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0017_entry_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='passwords',
            field=models.CharField(default='', max_length=50),
        ),
    ]
