# Generated by Django 4.0.4 on 2022-12-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatapp', '0018_alter_entry_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contact',
            field=models.FloatField(max_length=50),
        ),
    ]
